### ISSUE TITLE
Update the library to run on a >=14.0.0 Node image

### ISSUE THREAD

**Issue by Ibabalola** [Capgemini/dcx-react-library#297]
Please update the library to run on a >=14.0.0 Node image

- please resolve all needed package upgrades once changed

```yml
jobs:
  build:
    docker:
      - image: circleci/node:12.22.0
```

Please create your branch from release/0.6
```sh
git checkout release/0.6
git pull
git checkout -b 'feature/node-upgrade'
```
